
network:
  n_populations: 4

  C_matrix:
    - [16.0, 16.0, 96.0, 80.0]
    - [16.0, 16.0, 96.0, 80.0]
    - [16.0, 16.0, 96.0, 80.0]
    - [40.0, 40.0, 240.0, 80.0]

  J_matrix:
    - [0.56568542, 0.02828427, 0.02828427, -0.37476659]
    - [0.02828427, 0.56568542, 0.02828427, -0.37476659]
    - [0.02828427, 0.02828427, 0.02828427, -0.37476659]
    - [0.08838835, 0.08838835, 0.08838835, -0.34294679]

  Jab_ext:
    - 0.51265242
    - 0.51265242
    - 0.51265242
    - 0.45608387

  Cab_ext:
    - 128
    - 128
    - 128
    - 128

  nu_ext:
    - 7.0
    - 7.0
    - 7.0
    - 7.0

  tau_m:
    - 0.02
    - 0.02
    - 0.02
    - 0.02

  tau_s:
    - 0.005
    - 0.005
    - 0.005
    - 0.005

  threshold:
    - 4.86
    - 4.86
    - 4.86
    - 5.98

  reset_potential:
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  tau_ref: 0.005
  delta: 0

runner:
