init_params:
  n_neurons: 2000
  n_excitatory: 1600
  n_inhibitory: 400

architecture:
  network:
    tau_membrane: 0.02
    tau_synaptic: 0.005
    tau_refractory: 0.005
    threshold:
      - 1.5
      - 0.75
    reset_voltage: 0.
    j_ext:
      - 2.3
      - 2.3
      - 0.
      - 0.

  clusters:
    n_excitatory_background: 160
    n_inhibitory_background: 40
    n_clusters: 18
    connectivity_fraction_probs:
      - 0.2
      - 0.5
      - 0.5
      - 0.5

    j_baseline:
      - 0.63
      - 0.63
      - -1.9
      - -3.8

    j_potentiated:
      - 15.75
      - 5.45
      - 6.25
      - 5.0

    potentiate: True

external_currents:
  c_ext:
    - 320
    - 320
    - 0
    - 0

  nu_ext_baseline:
    - 7.
    - 7.
    - 0.
    - 0.

settings:
  save: False
  plot: False
  save_dir: simulations
  sim_name: mf_18
  random_seed: 256

arousal:
  level: 0.001
  L: .75
  x_0: .2
  k: 1.25
  M: 13.125
