
network:
  n_clusters: 4

  c_matrix:
    - [16, 16, 96, 80]
    - [16, 16, 96, 80]
    - [16, 16, 96, 80]
    - [40, 40, 240, 80]

  j_matrix:
    - [0.56568542, 0.02828427, 0.02828427, -0.37476659]
    - [0.02828427, 0.56568542, 0.02828427, -0.37476659]
    - [0.02828427, 0.02828427, 0.02828427, -0.37476659]
    - [0.08838835, 0.08838835, 0.08838835, -0.34294679]

  j_ext:
    - 0.51265242
    - 0.51265242
    - 0.51265242
    - 0.45608387

  c_ext:
    - 128
    - 128
    - 128
    - 128

  nu_ext:
    - 7.0
    - 7.0
    - 7.0
    - 7.0

  tau_membrane:
    - 0.02
    - 0.02
    - 0.02
    - 0.02

  tau_synaptic:
    - 0.005
    - 0.005
    - 0.005
    - 0.005

  threshold:
    - 4.86
    - 4.86
    - 4.86
    - 5.98

  reset_voltage:
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  tau_refractory: 0.005

runner:
  mode: effective
  effective:
    focus_pops:
      - 0
      - 1
    focus_nu_limits:
      - [0., 60.]
      - [0., 60.]
    focus_nu_density:
      - 0.5
      - 0.5
    ambient_nu_init:
      - 3.
      - 4.
  simple:
    nu_init:
      - 60.
      - 0.
      - 1.
      - 16.

sweep:
  sweep_param: j
  sweep_mode: shift
  sweep_vals: [0, 30, 0.5]
  read_vals_as: range
