init_params:
        delta_t: .0005
        duration_sec: 30
        mechanism: analytic
        n_neurons: 2000
        n_excitatory: 1600
        n_inhibitory: 400

architecture:
  network:
    tau_membrane: 0.02
    tau_synaptic: 0.005
    tau_refractory: 0.005
    threshold:
      - 1.5
      - 0.75
    reset_voltage: 0.0
    j_ext:
      - 2.3  # from excitatory
      - 2.3
      - 0.
      - 0.

  clusters:
    n_excitatory_background: 160
    n_inhibitory_background: 40
    n_clusters: 18
    total_pops: 38
    connectivity_fraction_probs:
      - 0.2
      - 0.5
      - 0.5
      - 0.5

    j_baseline:
      - 0.63
      - 0.63
      - -1.9
      - -3.8

    j_potentiated:
      - 16.85
      - 5.45
      - 6.25
      - 5.0

external_currents:
  c_ext:
    - 320  # from excitatory
    - 320
    - 0
    - 0

  nu_ext_baseline:
    - 7.  # to excitatory
    - 7.  # to inhibitory
    - 0.
    - 0.

stimulus:
  stimulus_shape: diff2exp  # or linear or box
  onsets:
  amplitude: 0.
  stimulated_clusters_prob: 0.5
  stimulated_neuron_prob: 0.5
  tau_rise: 0.075
  tau_decay: 0.1

settings:
  save: False
  plot: False
  save_dir:
  sim_name:
  random_seed:

arousal:
  level: 0.3
  L: .75
  x_0: .2
  k: 1.25
  M: 13.125


perturbation:
  j_potentiated:
    vectors:
      - [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    involved_clusters:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
    params: [0.1]
