architecture:
  network:
    tau_membrane: 0.02
    tau_synaptic: 0.005
    tau_refractory: 0.005
    threshold:
      - 1.5
      - 0.75
    reset_voltage: 0.0
    j_ext:
      - 2.3
      - 2.3
      - 0.0
      - 0.0

  clusters:
    n_excitatory_background: 160
    n_inhibitory_background: 40
    n_clusters: 18
    connectivity_fraction_probs:
      - 0.2
      - 0.5
      - 0.5
      - 0.5
    j_baseline:
      - 0.63
      - 0.63
      - -1.9
      - -3.8
    j_potentiated:
      - 15.75
      - 5.45
      - 6.25
      - 5.0

stimulus:
  stimulus_shape: diff2exp  # or linear of box
  onset: 1.0
  duration: 10.0
  amplitude: 0.05
  stimulated_neurons:
  tau_rise: 0.075
  tau_decay: 0.1

external_currents:
  c_ext:
    - 320
    - 320
    - 0
    - 0
  nu_ext_baseline:
    - 7.0
    - 7.0
    - 0.0
    - 0.0

simulation:
  delta_t: 0.001
  duration_sec: 10.0
  mechanism: analytic  # or euler
  random_seed: 256
  n_neurons: 2000
  n_excitatory: 1600

settings:
  save_dir: test_sim
  sim_name: sim_name
